definitions:
  mango.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/{id}:
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: data
        in: query
        name: data
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mango.Response'
      summary: 测试get接口
    post:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: data
        in: query
        name: data
        required: true
        type: integer
      - description: Data
        in: body
        name: data
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mango.Response'
      summary: 测试post接口
swagger: "2.0"
